T_A=$(EPICS_HOST_ARCH)
TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#----------------------------------------------------

#DB_INSTALLS += opal1000.proto
#DB_INSTALLS += hama-orca-flash4_0.proto
#DB_INSTALLS += pulnix6740.proto
#DB_INSTALLS += pulnix4200.proto
#DB_INSTALLS += up685.proto
#DB_INSTALLS += up900.proto

include $(TOP)/configure/RULES
#include $(TOP)/configure/RULES.copy
#----------------------------------------
#  ADD RULES AFTER THIS LINE

